FROM oven/bun:1.2.4 AS base
WORKDIR /app

# 前端构建
FROM base AS web-builder
WORKDIR /app/apps/web
COPY apps/web/package.json ./
COPY apps/web/bun.lock ./
RUN bun install

COPY apps/web/*.ts ./
COPY apps/web/*.json ./
COPY apps/web/index.html ./
COPY apps/web/src ./src

RUN bun run build

# 生产环境
FROM nginx:alpine AS web
COPY --from=web-builder /app/apps/web/dist /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
