version: '3.8'

services:
  server:
    build:
      context: ..
      dockerfile: docker/Dockerfile.server
    container_name: content-publish-server
    env_file:
      - .env.docker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      NODE_ENV: production
      PORT: 3000
    ports:
      - "50001:3000"
    volumes:
      - ../content:/app/content
    networks:
      - web_net

networks:
  web_net:
    external: true
